//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace template
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingRequest
    {
        public string ReqName { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Skill { get; set; }
    }
}
